// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Werkcollege03.Oef03.Data;

namespace Werkcollege03.Oef03.Migrations
{
    [DbContext(typeof(Werkcollege03Oef03Context))]
    [Migration("20200402145420_Initial-Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Werkcollege03.Oef03.Models.Punt", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Score");

                    b.Property<int?>("StudentID");

                    b.Property<int?>("VakID");

                    b.HasKey("ID");

                    b.HasIndex("StudentID");

                    b.HasIndex("VakID");

                    b.ToTable("Punten");
                });

            modelBuilder.Entity("Werkcollege03.Oef03.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naam");

                    b.HasKey("ID");

                    b.ToTable("Studenten");
                });

            modelBuilder.Entity("Werkcollege03.Oef03.Models.Vak", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naam");

                    b.HasKey("ID");

                    b.ToTable("Vakken");
                });

            modelBuilder.Entity("Werkcollege03.Oef03.Models.Punt", b =>
                {
                    b.HasOne("Werkcollege03.Oef03.Models.Student")
                        .WithMany("Punten")
                        .HasForeignKey("StudentID");

                    b.HasOne("Werkcollege03.Oef03.Models.Vak", "Vak")
                        .WithMany()
                        .HasForeignKey("VakID");
                });
#pragma warning restore 612, 618
        }
    }
}
